#!/bin/bash
#SBATCH --job-name=precompute_embeddings
#SBATCH --account=def-cfwelch
#SBATCH --gres=gpu:h100:1
#SBATCH --cpus-per-task=6
#SBATCH --mem=96G
#SBATCH --time=5:00:00
#SBATCH --mail-user=bhuiyr2@mcmaster.ca
#SBATCH --mail-type=BEGIN,END
#SBATCH --output=ft_bert_%j.out

module load python/3.11
module load StdEnv/2023
module load gcc/12.3
module load cuda/12.2
module load cudnn/9.2.1.18
module load arrow/21.0.0

source env/bin/activate
python ./src/precompute_comment_embeddings.py \
--dirname='dataset/amit_filtered_history/' \
--output_dir='dataset/embeddings/' \
--embed_sentences=false \
--output_file_name='precomputed_comment_embeddings_postlevel' \


python ./src/precompute_comment_embeddings.py \
--dirname='dataset/amit_filtered_history/' \
--output_dir='dataset/embeddings/' \
--embed_sentences=true \
--output_file_name='precomputed_comment_embeddings_sentlevel' \